ln -s "$(pwd)/.clang-format" "$HOME/.clang-format"
ln -s "$(pwd)/.nvimrc" "$HOME/.nvimrc"
ln -s "$(pwd)/.vimrc" "$HOME/.vimrc"
ln -s "$(pwd)/.zshrc" "$HOME/.zshrc"

ln -s "$(pwd)/alacritty" "$HOME/.config/alacritty"
ln -s "$(pwd)/clash" "$HOME/.config/clash"
ln -s "$(pwd)/i3" "$HOME/.config/i3"
ln -s "$(pwd)/i3status" "$HOME/.config/i3status"
ln -s "$(pwd)/kitty" "$HOME/.config/kitty"
ln -s "$(pwd)/nvim" "$HOME/.config/nvim"
ln -s "$(pwd)/picom" "$HOME/.config/picom"
ln -s "$(pwd)/polybar" "$HOME/.config/polybar"
ln -s "$(pwd)/ranger" "$HOME/.config/ranger"
