rm "$HOME/.clang-format"
ln -s "$(pwd)/.clang-format" "$HOME/.clang-format"
rm "$HOME/.nvimrc"
ln -s "$(pwd)/.nvimrc" "$HOME/.nvimrc"
rm "$HOME/.vimrc"
ln -s "$(pwd)/.vimrc" "$HOME/.vimrc"
rm "$HOME/.zshrc"
ln -s "$(pwd)/.zshrc" "$HOME/.zshrc"


rm -rf "$HOME/.config/alacritty"
ln -s "$(pwd)/alacritty" "$HOME/.config/alacritty"
rm -rf "$HOME/.config/i3"
ln -s "$(pwd)/i3" "$HOME/.config/i3"
rm -rf "$HOME/.config/i3status"
ln -s "$(pwd)/i3status" "$HOME/.config/i3status"
rm -rf "$HOME/.config/kitty"
ln -s "$(pwd)/kitty" "$HOME/.config/kitty"
rm -rf "$HOME/.config/nvim"
ln -s "$(pwd)/nvim" "$HOME/.config/nvim"
rm -rf "$HOME/.config/picom"
ln -s "$(pwd)/picom" "$HOME/.config/picom"
rm -rf "$HOME/.config/polybar"
ln -s "$(pwd)/polybar" "$HOME/.config/polybar"
rm -rf "$HOME/.config/ranger"
ln -s "$(pwd)/ranger" "$HOME/.config/ranger"


mkdir "$HOME/.config/clash"
ln -s "$(pwd)/clash/clash.service" "$HOME/.config/clash/clash.service"
ln -s "$(pwd)/clash/start-clash.sh" "$HOME/.config/clash/start-clash.sh"
ln -s "$(pwd)/clash/stop-clash.sh" "$HOME/.config/clash/stop-clash.sh"
