local U = require("utils")

U.map("n", "<CR>", 'defx#do_action("open")', { expr = true })
U.map("n", "c", 'defx#do_action("copy")', { expr = true })
U.map("n", "m", 'defx#do_action("move")', { expr = true })
U.map("n", "p", 'defx#do_action("paste")', { expr = true })
U.map("n", "l", 'defx#do_action("open")', { expr = true })
U.map("n", "E", 'defx#do_action("open","vsplit")', { expr = true })
U.map("n", "P", 'defx#do_action("preview")', { expr = true })
U.map("n", "o", "defx#do_action('open_tree','toggle')", { expr = true })
U.map("n", "K", "defx#do_action('new_directory')", { expr = true })
U.map("n", "N", "defx#do_action('new_file')", { expr = true })
U.map("n", "M", "defx#do_action('new_multiple_files')", { expr = true })
U.map("n", "C", "defx#do_action('toggle_columns', 'mark:indent:icon:filename:type:size:time')", { expr = true })
U.map("n", "S", "defx#do_action('toggle_sort','time')", { expr = true })
U.map("n", "d", "defx#do_action('remove')", { expr = true })
U.map("n", "r", "defx#do_action('rename')", { expr = true })
U.map("n", "!", "defx#do_action('execute_command')", { expr = true })
U.map("n", "x", "defx#do_action('execute_system')", { expr = true })
U.map("n", "yy", "defx#do_action('yank_path')", { expr = true })
U.map("n", ".", "defx#do_action('toggle_ignored_files')", { expr = true })
U.map("n", ";", "defx#do_action('repeat')", { expr = true })
U.map("n", "h", "defx#do_action('cd', ['..'])", { expr = true })
U.map("n", "~", "defx#do_action('cd')", { expr = true })
U.map("n", "q", "defx#do_action('quit')", { expr = true })
U.map("n", "<Space>", "defx#do_action('toggle_select')", { expr = true })
U.map("n", "*", "defx#do_action('toggle_select_all')", { expr = true })
U.map("n", "j", "line('.') == line('$') ? 'gg' : 'j'", { expr = true })
U.map("n", "k", "line('.') == 1 ? 'G' : 'K'", { expr = true })
U.map("n", "<C-l>", "defx#do_action('redraw)", { expr = true })
U.map("n", "<C-g>", "defx#do_action('print')", { expr = true })
U.map("n", "cd", "defx#do_action('change_vim_cwd')", { expr = true })
